feat: add addition calculator
paul-schuhm/tp1-mds-git-workflow-calculatrice pull request #3
Opened 2023-02-23 15:12 UTC by Kalvin56

2023-02-27 09:30 UTC, paul-schuhm commented on index.html
> +
Remonter la balise `script` dans la balise `body`

2023-02-27 09:33 UTC, paul-schuhm commented on index.js
> +result.innerHTML = parseInt(leftOperation.value) + parseInt(rightOperation.value);
Ce code va être difficile à maintenir (cf développer des nouvelles opérations pour la calculatrice). En effet, tu utilises ici une variable globale `result` qui est ensuite modifiée dans le reste du code, à l'intérieur des callbacks sur tes écouteurs d'évènement. Tu as du d'ailleurs dupliquer du code, ce qui est un mauvais signe. 

Pourrais tu améliorer cela en écrivant des fonctions dédiées (une fonction qui calcule le résultat, une fonction qui écrit le résultat dans la balise html dédiée) ?

2023-02-27 09:35 UTC, paul-schuhm commented on index.js
> +leftOperation.addEventListener("change", ($event) => {
Attention au code dupliqué ! `rightOperation` et `leftOperation` sont, dans le cas de l'addition tout à fait symétriques. Pourquoi ne pas déplacer le code de la callback dans une fonction car c'est le même ?

2023-02-27 09:39 UTC, paul-schuhm commented on index.js
> +rightOperation.addEventListener("change", ($event) => {
Le check sur les valeurs (et l'utilisation de `parseInt`) sont les bienvenues ! Il y a un effort de contrôle des input et c'est une très bonne chose. L'usage du `parseInt` n'est pas anodin, il introduit une contrainte forte sur notre calculatrice: impossible d'additionner des nombres à virgule flottante. On aimerait pouvoir faire l'addition `1.1 + 2` par exemple.

2023-02-27 09:41 UTC, paul-schuhm requested changes
Merci pour ta proposition, et l'effort entamé sur le contrôle des inputs utilisateurs est apprécié.  Voir les différents points adressés dans les commentaires. Concernant le message du commit, pourrais tu le formater en suivant les pratiques vues (cf support de cours). Le prefix `feat:` notamment n'est pas utile.

2023-03-01 08:36 UTC, Kalvin56 commented on index.js
> +result.innerHTML = parseInt(leftOperation.value) + parseInt(rightOperation.value);
Le code a été modifié, 3 fonctions ont été ajoutées (verify, calculate et writeResult)

2023-03-01 08:36 UTC, Kalvin56 commented on index.js
> +leftOperation.addEventListener("change", ($event) => {
Utilisation de le fonction calculate dans chaque listener

2023-03-01 08:39 UTC, Kalvin56 commented on index.html
> +
La balise script a été déplacée

2023-03-01 08:59 UTC, paul-schuhm commented on index.html
> +
Ok

2023-03-01 09:00 UTC, paul-schuhm commented on index.js
> +const verify = (value) => {
Une très bonne initiative de découper le travail en plusieurs fonctions élémentaires

2023-03-01 09:00 UTC, paul-schuhm commented on index.js
> +const verify = (value) => {
Attention, l'usage de `parseInt` empeche de faire des calculs avec nombres à virgule flottante

2023-03-01 09:01 UTC, paul-schuhm commented on index.js
> +  return 0
Ici on fait un choix d'un comportement par défaut. Pourquoi pas mais ce serait intéressant de documenter ce choix et de ses implications sur les calculs ? (par exemple dans le corps du commit)

2023-03-01 09:04 UTC, paul-schuhm commented on index.js
> +const writeResult = (value) => {
Excellent ! Une fonction dédiée à écrire sur le DOM (effets de bords)

2023-03-01 09:04 UTC, paul-schuhm requested changes
Merci pour les retours. Bonne initiative, j'aime l'idée d'avoir des fonctions bien atomiques pour vérifier les input, une pour écrire sur le DOM. Seulement quelques modifications indiquées en commentaire et ok pour moi

2023-06-21 08:22 UTC, closed without merging